/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 **/
package A3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author geovane
 */
public class TelaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form TelaPrincipal
     */
    LocalDateTime minhaData = LocalDateTime.now();
    DateTimeFormatter Mes = DateTimeFormatter.ofPattern("MMM");
    DateTimeFormatter Ano = DateTimeFormatter.ofPattern("yyyy");
    String formattedDate1 = minhaData.format(Ano);
    String formattedDate = minhaData.format(Mes);
    int id_usuario;
    Usuario usuario = new Usuario();
    ResultSet rs;
    public void setText(String usuario,int id,double saldo_flutuante,double gastoessencial,double gastonao,double gastototal){
        jLabel3.setText("@"+usuario);
        id_usuario = id;
        jLabel1.setText("R$"+Double.toString(saldo_flutuante));
        lGastoEssencial.setText("Gasto Essencial: R$ "+Double.toString(gastoessencial));
        lGastoNaoEssencial.setText("Gasto Não Essencial: R$ "+Double.toString(gastonao));
        lGastoTotal.setText("Gastos: R$ "+Double.toString(gastototal));
        
    }
    public TelaPrincipal() {
        initComponents();
       
        
        
        
       
    }
    {
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelAdicionarSaldo = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        AdicionaValor = new javax.swing.JTextField();
        BntAdicionarSaldo = new javax.swing.JButton();
        bntSairAdicionaSaldo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PainelAdicionaGasto = new javax.swing.JDialog();
        lValorGasto = new javax.swing.JLabel();
        GastoCampoTexto = new javax.swing.JTextField();
        BntAdicionarGasto = new javax.swing.JButton();
        BntVoltarGasto = new javax.swing.JButton();
        BoxGasto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PainelAdicionaDinheiro = new javax.swing.JDialog();
        ValorDInheiro = new javax.swing.JLabel();
        AdicionaDinheiro = new javax.swing.JTextField();
        BntAdicionaDinheiro = new javax.swing.JButton();
        bntVoltarDinheiro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        PainelComparacao = new javax.swing.JDialog();
        Mes1ComboBox = new javax.swing.JComboBox<>();
        Mes2ComboBox = new javax.swing.JComboBox<>();
        Ano1ComboBox = new javax.swing.JComboBox<>();
        Ano2ComboBox = new javax.swing.JComboBox<>();
        lSaldoFixoComp = new javax.swing.JLabel();
        lGastoEssencialComp = new javax.swing.JLabel();
        lGastoNaoEssenComp = new javax.swing.JLabel();
        lGastoTotalComp = new javax.swing.JLabel();
        CompararBotaoAcao = new javax.swing.JButton();
        lGastoEssencialComp2 = new javax.swing.JLabel();
        lGastoNaoEssencialComp2 = new javax.swing.JLabel();
        lGastoTotalComp2 = new javax.swing.JLabel();
        lSaldoFixoComp2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lGastoEssencial = new javax.swing.JLabel();
        lGastoNaoEssencial = new javax.swing.JLabel();
        lGastoTotal = new javax.swing.JLabel();
        BntSaldoAdiciona = new javax.swing.JButton();
        BntGastoPainel = new javax.swing.JButton();
        BntAdicionarDinheiro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        PainelAdicionarSaldo.setAutoRequestFocus(false);
        PainelAdicionarSaldo.setBackground(new java.awt.Color(3, 154, 154));
        PainelAdicionarSaldo.setResizable(false);
        PainelAdicionarSaldo.setSize(new java.awt.Dimension(400, 300));

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Valor:");

        AdicionaValor.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        AdicionaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionaValorActionPerformed(evt);
            }
        });
        AdicionaValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AdicionaValorKeyTyped(evt);
            }
        });

        BntAdicionarSaldo.setBackground(new java.awt.Color(74, 194, 62));
        BntAdicionarSaldo.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        BntAdicionarSaldo.setForeground(new java.awt.Color(254, 254, 254));
        BntAdicionarSaldo.setText("Adicionar");
        BntAdicionarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAdicionarSaldoActionPerformed(evt);
            }
        });

        bntSairAdicionaSaldo.setBackground(new java.awt.Color(247, 46, 53));
        bntSairAdicionaSaldo.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bntSairAdicionaSaldo.setForeground(new java.awt.Color(254, 254, 254));
        bntSairAdicionaSaldo.setText("Sair");
        bntSairAdicionaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairAdicionaSaldoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Digite o Valor do Seu Salario:");

        javax.swing.GroupLayout PainelAdicionarSaldoLayout = new javax.swing.GroupLayout(PainelAdicionarSaldo.getContentPane());
        PainelAdicionarSaldo.getContentPane().setLayout(PainelAdicionarSaldoLayout);
        PainelAdicionarSaldoLayout.setHorizontalGroup(
            PainelAdicionarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionarSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PainelAdicionarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAdicionarSaldoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(PainelAdicionarSaldoLayout.createSequentialGroup()
                        .addGroup(PainelAdicionarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAdicionarSaldoLayout.createSequentialGroup()
                                .addComponent(BntAdicionarSaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntSairAdicionaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AdicionaValor))
                        .addGap(26, 26, 26))))
        );
        PainelAdicionarSaldoLayout.setVerticalGroup(
            PainelAdicionarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionarSaldoLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(PainelAdicionarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AdicionaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAdicionarSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntAdicionarSaldo)
                    .addComponent(bntSairAdicionaSaldo))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        PainelAdicionaGasto.setSize(new java.awt.Dimension(400, 300));

        lValorGasto.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lValorGasto.setForeground(new java.awt.Color(254, 254, 254));
        lValorGasto.setText("VALOR:");

        GastoCampoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GastoCampoTextoKeyTyped(evt);
            }
        });

        BntAdicionarGasto.setBackground(new java.awt.Color(74, 194, 62));
        BntAdicionarGasto.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        BntAdicionarGasto.setForeground(new java.awt.Color(254, 254, 254));
        BntAdicionarGasto.setText("Adicionar");
        BntAdicionarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAdicionarGastoActionPerformed(evt);
            }
        });

        BntVoltarGasto.setBackground(new java.awt.Color(247, 46, 53));
        BntVoltarGasto.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        BntVoltarGasto.setForeground(new java.awt.Color(254, 254, 254));
        BntVoltarGasto.setText("Voltar");
        BntVoltarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntVoltarGastoActionPerformed(evt);
            }
        });

        BoxGasto.setBackground(new java.awt.Color(0, 102, 102));
        BoxGasto.setForeground(new java.awt.Color(254, 254, 254));
        BoxGasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Essencial", "Não-Essencial" }));
        BoxGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxGastoActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Escolhe o tipo de Gasto:");

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Digite quanto foi o gasto:");

        javax.swing.GroupLayout PainelAdicionaGastoLayout = new javax.swing.GroupLayout(PainelAdicionaGasto.getContentPane());
        PainelAdicionaGasto.getContentPane().setLayout(PainelAdicionaGastoLayout);
        PainelAdicionaGastoLayout.setHorizontalGroup(
            PainelAdicionaGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionaGastoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lValorGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAdicionaGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GastoCampoTexto)
                    .addGroup(PainelAdicionaGastoLayout.createSequentialGroup()
                        .addComponent(BntAdicionarGasto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(BntVoltarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelAdicionaGastoLayout.createSequentialGroup()
                        .addGroup(PainelAdicionaGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(BoxGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelAdicionaGastoLayout.setVerticalGroup(
            PainelAdicionaGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionaGastoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAdicionaGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValorGasto)
                    .addComponent(GastoCampoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(BoxGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(PainelAdicionaGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntAdicionarGasto)
                    .addComponent(BntVoltarGasto))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        PainelAdicionaDinheiro.setSize(new java.awt.Dimension(400, 300));

        ValorDInheiro.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        ValorDInheiro.setForeground(new java.awt.Color(254, 254, 254));
        ValorDInheiro.setText("VALOR:");

        AdicionaDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionaDinheiroActionPerformed(evt);
            }
        });
        AdicionaDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AdicionaDinheiroKeyTyped(evt);
            }
        });

        BntAdicionaDinheiro.setBackground(new java.awt.Color(74, 194, 62));
        BntAdicionaDinheiro.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        BntAdicionaDinheiro.setForeground(new java.awt.Color(254, 254, 254));
        BntAdicionaDinheiro.setText("Adicionar");
        BntAdicionaDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAdicionaDinheiroActionPerformed(evt);
            }
        });

        bntVoltarDinheiro.setBackground(new java.awt.Color(247, 46, 53));
        bntVoltarDinheiro.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        bntVoltarDinheiro.setForeground(new java.awt.Color(254, 254, 254));
        bntVoltarDinheiro.setText("Sair");
        bntVoltarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarDinheiroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Adicione o quanto ganhou a mais:");

        javax.swing.GroupLayout PainelAdicionaDinheiroLayout = new javax.swing.GroupLayout(PainelAdicionaDinheiro.getContentPane());
        PainelAdicionaDinheiro.getContentPane().setLayout(PainelAdicionaDinheiroLayout);
        PainelAdicionaDinheiroLayout.setHorizontalGroup(
            PainelAdicionaDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionaDinheiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ValorDInheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAdicionaDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAdicionaDinheiroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PainelAdicionaDinheiroLayout.createSequentialGroup()
                        .addComponent(BntAdicionaDinheiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(bntVoltarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AdicionaDinheiro))
                .addContainerGap())
        );
        PainelAdicionaDinheiroLayout.setVerticalGroup(
            PainelAdicionaDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdicionaDinheiroLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(PainelAdicionaDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorDInheiro)
                    .addComponent(AdicionaDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(PainelAdicionaDinheiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntAdicionaDinheiro)
                    .addComponent(bntVoltarDinheiro))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        PainelComparacao.setSize(new java.awt.Dimension(793, 392));

        Mes1ComboBox.setBackground(new java.awt.Color(0, 102, 102));
        Mes1ComboBox.setForeground(new java.awt.Color(254, 254, 254));
        Mes1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" }));
        Mes1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mes1ComboBoxActionPerformed(evt);
            }
        });

        Mes2ComboBox.setBackground(new java.awt.Color(0, 102, 102));
        Mes2ComboBox.setForeground(new java.awt.Color(254, 254, 254));
        Mes2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" }));
        Mes2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mes2ComboBoxActionPerformed(evt);
            }
        });

        Ano1ComboBox.setBackground(new java.awt.Color(0, 102, 102));
        Ano1ComboBox.setForeground(new java.awt.Color(254, 254, 254));
        Ano1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026" }));
        Ano1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ano1ComboBoxActionPerformed(evt);
            }
        });

        Ano2ComboBox.setBackground(new java.awt.Color(0, 102, 102));
        Ano2ComboBox.setForeground(new java.awt.Color(254, 254, 254));
        Ano2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026" }));
        Ano2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ano2ComboBoxActionPerformed(evt);
            }
        });

        lSaldoFixoComp.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lSaldoFixoComp.setText("Saldo:                                   R$2400;");
        lSaldoFixoComp.setToolTipText("");

        lGastoEssencialComp.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoEssencialComp.setText("Gasto Essencial:             R$1200.59");

        lGastoNaoEssenComp.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoNaoEssenComp.setText("Gasto Não Essencial:    R$500");

        lGastoTotalComp.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoTotalComp.setText("Gasto Total:                      R$1700.59");

        CompararBotaoAcao.setBackground(new java.awt.Color(0, 102, 102));
        CompararBotaoAcao.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        CompararBotaoAcao.setForeground(new java.awt.Color(254, 254, 254));
        CompararBotaoAcao.setText("Comparar");
        CompararBotaoAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompararBotaoAcaoActionPerformed(evt);
            }
        });

        lGastoEssencialComp2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoEssencialComp2.setText("R$700");

        lGastoNaoEssencialComp2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoNaoEssencialComp2.setText("R$600");

        lGastoTotalComp2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoTotalComp2.setText("R$1500");

        lSaldoFixoComp2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lSaldoFixoComp2.setText("R$2400");

        javax.swing.GroupLayout PainelComparacaoLayout = new javax.swing.GroupLayout(PainelComparacao.getContentPane());
        PainelComparacao.getContentPane().setLayout(PainelComparacaoLayout);
        PainelComparacaoLayout.setHorizontalGroup(
            PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelComparacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelComparacaoLayout.createSequentialGroup()
                        .addComponent(Mes1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ano1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(CompararBotaoAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelComparacaoLayout.createSequentialGroup()
                                .addComponent(Mes2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Ano2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelComparacaoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lSaldoFixoComp2)
                                    .addComponent(lGastoTotalComp2)
                                    .addComponent(lGastoEssencialComp2)
                                    .addComponent(lGastoNaoEssencialComp2)))))
                    .addComponent(lSaldoFixoComp)
                    .addComponent(lGastoTotalComp)
                    .addComponent(lGastoEssencialComp)
                    .addComponent(lGastoNaoEssenComp))
                .addGap(24, 24, 24))
        );
        PainelComparacaoLayout.setVerticalGroup(
            PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelComparacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompararBotaoAcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PainelComparacaoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mes1ComboBox)
                            .addComponent(Ano1ComboBox)
                            .addComponent(Ano2ComboBox)
                            .addComponent(Mes2ComboBox))))
                .addGap(135, 135, 135)
                .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGastoNaoEssenComp)
                    .addComponent(lGastoNaoEssencialComp2))
                .addGap(18, 18, 18)
                .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGastoEssencialComp)
                    .addComponent(lGastoEssencialComp2))
                .addGap(18, 18, 18)
                .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGastoTotalComp)
                    .addComponent(lGastoTotalComp2))
                .addGap(18, 18, 18)
                .addGroup(PainelComparacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSaldoFixoComp)
                    .addComponent(lSaldoFixoComp2))
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 551));

        lGastoEssencial.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoEssencial.setForeground(new java.awt.Color(254, 254, 254));
        lGastoEssencial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lGastoEssencial.setText("Gastos Essencial: R$");

        lGastoNaoEssencial.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoNaoEssencial.setForeground(new java.awt.Color(254, 254, 254));
        lGastoNaoEssencial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lGastoNaoEssencial.setText("Gasto Não Essencial: R$");

        lGastoTotal.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lGastoTotal.setForeground(new java.awt.Color(254, 254, 254));
        lGastoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lGastoTotal.setText("Gastos: R$");

        BntSaldoAdiciona.setBackground(new java.awt.Color(0, 102, 102));
        BntSaldoAdiciona.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        BntSaldoAdiciona.setForeground(new java.awt.Color(254, 255, 255));
        BntSaldoAdiciona.setText("+Saldo");
        BntSaldoAdiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntSaldoAdicionaActionPerformed(evt);
            }
        });

        BntGastoPainel.setBackground(new java.awt.Color(0, 102, 102));
        BntGastoPainel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        BntGastoPainel.setForeground(new java.awt.Color(254, 254, 254));
        BntGastoPainel.setText("+Gasto");
        BntGastoPainel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntGastoPainelActionPerformed(evt);
            }
        });

        BntAdicionarDinheiro.setBackground(new java.awt.Color(0, 102, 102));
        BntAdicionarDinheiro.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        BntAdicionarDinheiro.setForeground(new java.awt.Color(254, 254, 254));
        BntAdicionarDinheiro.setText("+Dinheiro");
        BntAdicionarDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAdicionarDinheiroActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Comparar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setPreferredSize(new java.awt.Dimension(910, 190));

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel3.setText("@");

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saldo: ");

        jButton2.setText("SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                .addGap(263, 263, 263)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(82, 82, 82))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lGastoNaoEssencial)
                    .addComponent(lGastoEssencial)
                    .addComponent(lGastoTotal))
                .addGap(393, 393, 393))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BntSaldoAdiciona, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addComponent(BntAdicionarDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addGap(64, 64, 64)
                        .addComponent(BntGastoPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BntAdicionarDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BntGastoPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BntSaldoAdiciona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(lGastoEssencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lGastoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lGastoNaoEssencial, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BntSaldoAdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntSaldoAdicionaActionPerformed
        // TODO add your handling code here:
        PainelAdicionarSaldo.setLocationRelativeTo(null);
        PainelAdicionarSaldo.setVisible(true);
        PainelAdicionarSaldo.getContentPane().setBackground(new java.awt.Color(3,154,154));
        
    }//GEN-LAST:event_BntSaldoAdicionaActionPerformed

    private void AdicionaValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdicionaValorKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789.";
        if(!caracteres.contains(evt.getKeyChar() + "")){
            evt.consume();
        }
    }//GEN-LAST:event_AdicionaValorKeyTyped

    private void bntSairAdicionaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairAdicionaSaldoActionPerformed
        // TODO add your handling code here:
        PainelAdicionarSaldo.dispose();
        AdicionaValor.setText("");
    }//GEN-LAST:event_bntSairAdicionaSaldoActionPerformed

    private void BntAdicionarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAdicionarSaldoActionPerformed
        String sql5 = "select saldo_inicial from "+formattedDate+"tb where usuario_id=? and ano=?";
        ConnectionFactory factory = new ConnectionFactory();
        usuario.setId_usuario(id_usuario);
        try(Connection con = factory.obtemConexao()){
            PreparedStatement ps = con.prepareStatement(sql5);
            ps.setInt(1,id_usuario);
            ps.setInt(2,Integer.parseInt(formattedDate1));
            rs = ps.executeQuery();
           
            if(rs.next()){
                double saldo_teste = rs.getDouble("saldo_inicial");
                if(AdicionaValor.getText().equalsIgnoreCase("")){
                    JOptionPane.showMessageDialog(null,"Não pode ser adicionado valor vazio");
                    
                } else if(saldo_teste>0){
                    JOptionPane.showMessageDialog(null,"Saldo já Adicionado esse mês");
                } else {
                    double valor = Double.parseDouble(AdicionaValor.getText());
                    usuario.setSaldo_fixo(valor);
                    usuario.setSaldo_usuario(valor);
                    usuario.AdicionaSaldo();
                    jLabel1.setText("R$"+Double.toString(valor));
                    PainelAdicionarSaldo.dispose();
                    AdicionaValor.setText("");
                }
            }
            
            

            } catch(SQLException ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_BntAdicionarSaldoActionPerformed

    private void BntGastoPainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntGastoPainelActionPerformed
        // TODO add your handling code here:
        PainelAdicionaGasto.setLocationRelativeTo(null);
        PainelAdicionaGasto.setVisible(true);
        PainelAdicionaGasto.setTitle("Adicione o gasto");
        PainelAdicionaGasto.getContentPane().setBackground(new java.awt.Color(3,154,154));
    }//GEN-LAST:event_BntGastoPainelActionPerformed

    private void BoxGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxGastoActionPerformed

    private void BntAdicionarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAdicionarGastoActionPerformed
        // TODO add your handling code here:
        //0= Essencial 1 = Não Essencial
        int selecao = BoxGasto.getSelectedIndex();
        String sql5 = "select saldo_inicial,saldo_flutuante,gasto_essencial,gasto_naoessencial,gastototal"
                + " from "+formattedDate+"tb where usuario_id=? and ano=?";
        ConnectionFactory factory = new ConnectionFactory();
        usuario.setId_usuario(id_usuario);
        try(Connection con = factory.obtemConexao()){
            PreparedStatement ps = con.prepareStatement(sql5);
            ps.setInt(1,usuario.getId_usuario());
            ps.setInt(2,Integer.parseInt(formattedDate1));
            rs = ps.executeQuery();
           
            if(rs.next()){
                double saldo_teste = rs.getDouble("saldo_inicial");
                double saldo_flutuante = rs.getDouble("saldo_flutuante");
                double gasto_essencial = rs.getDouble("gasto_essencial");
                double gasto_naoessencial = rs.getDouble("gasto_naoessencial");
                double gastototal = rs.getDouble("gastototal");
                if(GastoCampoTexto.getText().equalsIgnoreCase("")){
                    JOptionPane.showMessageDialog(null,"Não pode ser adicionado valor vazio");
                    
                } else if(saldo_teste==0){
                    JOptionPane.showMessageDialog(null,"Adicione o Saldo Primeiro");
                }
                //0 = Essencial 1 = Não Essencial
                else if(selecao==0){
                    double gastodigitado = Double.parseDouble(GastoCampoTexto.getText());
                    gasto_essencial = gastodigitado+gasto_essencial;
                    saldo_flutuante = saldo_flutuante-gastodigitado;
                    gastototal = gastodigitado+gastototal;
                    usuario.setGastos_essenciais(gasto_essencial);
                    usuario.setSaldo_usuario(saldo_flutuante);
                    usuario.setGastos_totais(gastototal);
                    usuario.AdicionaGastoEssencial();
                    jLabel1.setText("R$"+Double.toString(saldo_flutuante));
                    lGastoEssencial.setText("Gastos Essenciais: R$"+Double.toString(gasto_essencial));
                    lGastoTotal.setText("Gastos: R$"+Double.toString(gastototal));
                    
                    
                } else if(selecao==1){
                    double gastodigitado = Double.parseDouble(GastoCampoTexto.getText());
                    gasto_naoessencial = gastodigitado+gasto_naoessencial;
                    saldo_flutuante = saldo_flutuante-gastodigitado;
                    gastototal = gastodigitado+gastototal;
                    usuario.setGastos_naoessenciais(gasto_naoessencial);
                    usuario.setSaldo_usuario(saldo_flutuante);
                    usuario.setGastos_totais(gastototal);
                    usuario.AdicionaGastoNaoEssencial();
                    jLabel1.setText("R$"+Double.toString(saldo_flutuante));
                    lGastoNaoEssencial.setText("Gastos Não Essenciaais: R$"+Double.toString(gasto_naoessencial));
                    lGastoTotal.setText("Gastos: R$"+Double.toString(gastototal));
                    
                } else{
                    
                }
            }     
        } catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BntAdicionarGastoActionPerformed

    private void GastoCampoTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GastoCampoTextoKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789.";
        if(!caracteres.contains(evt.getKeyChar() + "")){
        evt.consume();
        }
    }//GEN-LAST:event_GastoCampoTextoKeyTyped

    private void BntAdicionarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAdicionarDinheiroActionPerformed
        // TODO add your handling code here:
        PainelAdicionaDinheiro.setLocationRelativeTo(null);
        PainelAdicionaDinheiro.setVisible(true);
        PainelAdicionaDinheiro.setTitle("Adicione o dinheiro a mais");
        PainelAdicionaDinheiro.getContentPane().setBackground(new java.awt.Color(3,154,154));
    }//GEN-LAST:event_BntAdicionarDinheiroActionPerformed

    private void AdicionaDinheiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdicionaDinheiroKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789.";
        if(!caracteres.contains(evt.getKeyChar() + "")){
        evt.consume();
        }
    }//GEN-LAST:event_AdicionaDinheiroKeyTyped

    private void BntVoltarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntVoltarGastoActionPerformed
        // TODO add your handling code here:
        PainelAdicionaGasto.dispose();
        AdicionaDinheiro.setText("");
    }//GEN-LAST:event_BntVoltarGastoActionPerformed

    private void AdicionaDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionaDinheiroActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_AdicionaDinheiroActionPerformed

    private void BntAdicionaDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAdicionaDinheiroActionPerformed
        // TODO add your handling code here:
        String sql5 = "select saldo_flutuante, saldo_inicial from "+formattedDate+"tb where usuario_id=? and ano=?";
        ConnectionFactory factory = new ConnectionFactory();
        usuario.setId_usuario(id_usuario);
        try(Connection con = factory.obtemConexao()){
            PreparedStatement ps = con.prepareStatement(sql5);
            ps.setInt(1,id_usuario);
            ps.setInt(2,Integer.parseInt(formattedDate1));
            rs = ps.executeQuery();
           
            if(rs.next()){
                double saldo_flutuante = rs.getDouble("saldo_flutuante");
                double saldo_inicial = rs.getDouble("saldo_inicial");
                if(AdicionaDinheiro.getText().equalsIgnoreCase("")){
                    JOptionPane.showMessageDialog(null,"Não pode ser adicionado valor vazio");
                    
                } else if(saldo_inicial==0){
                    JOptionPane.showMessageDialog(null,"Adicione o Saldo primeiro");
                }
                else  {
                    double dinheiro = Double.parseDouble(AdicionaDinheiro.getText());
                    saldo_flutuante = dinheiro+saldo_flutuante;
                    usuario.setSaldo_usuario(saldo_flutuante);
                    usuario.AdicionaDinheiro();
                    jLabel1.setText("R$"+Double.toString(saldo_flutuante));
                    PainelAdicionarSaldo.dispose();
                    AdicionaDinheiro.setText("");
                }
            }
            
            

            } catch(SQLException ex){
                ex.printStackTrace();
        }
    }//GEN-LAST:event_BntAdicionaDinheiroActionPerformed

    private void Ano1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ano1ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ano1ComboBoxActionPerformed

    private void Ano2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ano2ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ano2ComboBoxActionPerformed

    private void CompararBotaoAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompararBotaoAcaoActionPerformed
        // TODO add your handling code here:
        String mes1 = Mes1ComboBox.getSelectedItem().toString();
        String ano1s = Ano1ComboBox.getSelectedItem().toString();
        int ano1 = Integer.parseInt(ano1s);
        String tresprimeiros = mes1.substring(0,3);
        String sql5 = "select * from "+tresprimeiros+"tb where usuario_id=? and ano=?";
        ConnectionFactory factory = new ConnectionFactory();
        usuario.setId_usuario(id_usuario);
        try(Connection con = factory.obtemConexao()){
            PreparedStatement ps = con.prepareStatement(sql5);
            ps.setInt(1,id_usuario);
            ps.setInt(2,ano1);
            rs = ps.executeQuery();
            if(rs.next()){
                double saldo_inicial = rs.getDouble("saldo_inicial");
                double gasto_essencial = rs.getDouble("gasto_essencial");
                double gasto_naoessencial = rs.getDouble("gasto_naoessencial");
                double gastototal = rs.getDouble("gastototal");
                lSaldoFixoComp.setText("Saldo :R$"+Double.toString(saldo_inicial));
                lGastoEssencialComp.setText("Gasto Essencial:   R$"+Double.toString(gasto_essencial));
                lGastoNaoEssenComp.setText("Gastos não essenciais   R$"+Double.toString(gasto_naoessencial));
                lGastoTotalComp.setText("Total Gastos: R$"+Double.toString(gastototal));
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Dados não encontrada na data selecionada "+mes1+" ano "+ano1);
            }
        } catch(SQLException ex){
            ex.printStackTrace();
        }
        String mes2 = Mes2ComboBox.getSelectedItem().toString();
        String ano2s = Ano2ComboBox.getSelectedItem().toString();
        int ano2 = Integer.parseInt(ano2s);
        String tresprimeiros2 = mes2.substring(0,3);
        String sql6 = "select * from "+tresprimeiros2+"tb where usuario_id=? and ano=?";
        usuario.setId_usuario(id_usuario);
        try(Connection con = factory.obtemConexao()){
            PreparedStatement ps = con.prepareStatement(sql6);
            ps.setInt(1,id_usuario);
            ps.setInt(2,ano2);
            rs = ps.executeQuery();
            if(rs.next()){
                double saldo_inicial = rs.getDouble("saldo_inicial");
                double gasto_essencial = rs.getDouble("gasto_essencial");
                double gasto_naoessencial = rs.getDouble("gasto_naoessencial");
                double gastototal = rs.getDouble("gastototal");
                lSaldoFixoComp2.setText("R$"+Double.toString(saldo_inicial));
                lGastoEssencialComp2.setText("R$"+Double.toString(gasto_essencial));
                lGastoNaoEssencialComp2.setText("R$"+Double.toString(gasto_naoessencial));
                lGastoTotalComp2.setText("R$"+Double.toString(gastototal));
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Dados não encontrada na data selecionada "+mes2+" ano "+ano2);
            }
            } catch(SQLException ex){
                ex.printStackTrace();
            }
    }//GEN-LAST:event_CompararBotaoAcaoActionPerformed

    private void Mes1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mes1ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mes1ComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PainelComparacao.setLocationRelativeTo(null);
        PainelComparacao.setVisible(true);
        PainelComparacao.getContentPane().setBackground(new java.awt.Color(3,154,154));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AdicionaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdicionaValorActionPerformed

    private void Mes2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mes2ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mes2ComboBoxActionPerformed

    private void bntVoltarDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarDinheiroActionPerformed
        // TODO add your handling code here:
        PainelAdicionaDinheiro.setVisible(false);
        AdicionaDinheiro.setText("");
        
    }//GEN-LAST:event_bntVoltarDinheiroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaLoginUser login = new TelaLoginUser();
        login.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdicionaDinheiro;
    private javax.swing.JTextField AdicionaValor;
    private javax.swing.JComboBox<String> Ano1ComboBox;
    private javax.swing.JComboBox<String> Ano2ComboBox;
    private javax.swing.JButton BntAdicionaDinheiro;
    private javax.swing.JButton BntAdicionarDinheiro;
    private javax.swing.JButton BntAdicionarGasto;
    private javax.swing.JButton BntAdicionarSaldo;
    private javax.swing.JButton BntGastoPainel;
    private javax.swing.JButton BntSaldoAdiciona;
    private javax.swing.JButton BntVoltarGasto;
    private javax.swing.JComboBox<String> BoxGasto;
    private javax.swing.JButton CompararBotaoAcao;
    private javax.swing.JTextField GastoCampoTexto;
    private javax.swing.JComboBox<String> Mes1ComboBox;
    private javax.swing.JComboBox<String> Mes2ComboBox;
    private javax.swing.JDialog PainelAdicionaDinheiro;
    private javax.swing.JDialog PainelAdicionaGasto;
    private javax.swing.JDialog PainelAdicionarSaldo;
    private javax.swing.JDialog PainelComparacao;
    private javax.swing.JLabel ValorDInheiro;
    private javax.swing.JButton bntSairAdicionaSaldo;
    private javax.swing.JButton bntVoltarDinheiro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lGastoEssencial;
    private javax.swing.JLabel lGastoEssencialComp;
    private javax.swing.JLabel lGastoEssencialComp2;
    private javax.swing.JLabel lGastoNaoEssenComp;
    private javax.swing.JLabel lGastoNaoEssencial;
    private javax.swing.JLabel lGastoNaoEssencialComp2;
    private javax.swing.JLabel lGastoTotal;
    private javax.swing.JLabel lGastoTotalComp;
    private javax.swing.JLabel lGastoTotalComp2;
    private javax.swing.JLabel lSaldoFixoComp;
    private javax.swing.JLabel lSaldoFixoComp2;
    private javax.swing.JLabel lValorGasto;
    // End of variables declaration//GEN-END:variables
}
